"""スライド→画像変換モジュール。

LibreOfficeでpptx→PDF変換し、pdf2imageでPNG画像に変換する。
Streamlit UIでのプレビュー表示に使用。
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from PIL import Image

# macOSのLibreOfficeパス
_SOFFICE_PATHS = [
    "soffice",
    "/Applications/LibreOffice.app/Contents/MacOS/soffice",
    "/usr/bin/soffice",
    "/usr/local/bin/soffice",
]


def _find_soffice() -> str:
    """利用可能なsofficeコマンドのパスを返す。"""
    for path in _SOFFICE_PATHS:
        try:
            result = subprocess.run(
                [path, "--version"],
                capture_output=True, text=True, timeout=10,
            )
            if result.returncode == 0:
                return path
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    raise RuntimeError(
        "LibreOffice not found. Install it or add soffice to PATH."
    )


def render_slides(
    pptx_path: str | Path,
    output_dir: str | Path | None = None,
    dpi: int = 150,
) -> list[Path]:
    """pptxの全スライドをPNG画像に変換して返す。"""
    pptx_path = Path(pptx_path)
    if not pptx_path.exists():
        raise FileNotFoundError(f"File not found: {pptx_path}")

    if output_dir is None:
        output_dir = Path(tempfile.mkdtemp(prefix="slide_preview_"))
    else:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: LibreOfficeでPDF変換
    pdf_path = _pptx_to_pdf(pptx_path, output_dir)

    # Step 2: PDFをPNG画像に変換
    images = _pdf_to_images(pdf_path, output_dir, dpi)

    return images


def render_slide(
    pptx_path: str | Path,
    slide_index: int = 0,
    dpi: int = 150,
) -> Image.Image:
    """特定スライドをPIL Imageとして返す。"""
    pptx_path = Path(pptx_path)

    with tempfile.TemporaryDirectory(prefix="slide_render_") as tmpdir:
        pdf_path = _pptx_to_pdf(pptx_path, Path(tmpdir))
        images = _pdf_to_images(pdf_path, Path(tmpdir), dpi)

        if slide_index >= len(images):
            raise IndexError(f"Slide index {slide_index} out of range (total: {len(images)})")

        return Image.open(images[slide_index]).copy()


def _pptx_to_pdf(pptx_path: Path, output_dir: Path) -> Path:
    """LibreOfficeでpptxをPDFに変換。"""
    soffice = _find_soffice()
    result = subprocess.run(
        [
            soffice,
            "--headless",
            "--convert-to", "pdf",
            "--outdir", str(output_dir),
            str(pptx_path),
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"LibreOffice conversion failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )

    pdf_path = output_dir / f"{pptx_path.stem}.pdf"
    if not pdf_path.exists():
        # LibreOfficeが別名で出力する場合がある
        pdf_files = list(output_dir.glob("*.pdf"))
        if pdf_files:
            pdf_path = pdf_files[0]
        else:
            raise RuntimeError("PDF file not generated by LibreOffice")

    return pdf_path


def _pdf_to_images(pdf_path: Path, output_dir: Path, dpi: int) -> list[Path]:
    """PDFをページごとのPNG画像に変換。"""
    from pdf2image import convert_from_path

    pil_images = convert_from_path(str(pdf_path), dpi=dpi)

    image_paths: list[Path] = []
    for i, img in enumerate(pil_images):
        img_path = output_dir / f"slide_{i:03d}.png"
        img.save(str(img_path), "PNG")
        image_paths.append(img_path)

    return image_paths


def render_layout_previews(
    pptx_path: str | Path,
    dpi: int = 100,
) -> list[Image.Image]:
    """テンプレートの各レイアウトをプレビュー画像として返す。

    全レイアウトから1枚ずつスライドを含むpptxを一括生成し、
    まとめてレンダリングする。
    """
    from pptx import Presentation as PptxPresentation

    pptx_path = Path(pptx_path)
    source_prs = PptxPresentation(str(pptx_path))
    layout_count = len(source_prs.slide_layouts)

    with tempfile.TemporaryDirectory(prefix="layout_previews_") as tmpdir:
        tmp_pptx = Path(tmpdir) / "layouts.pptx"

        # 全レイアウトを1枚ずつスライドとして追加
        prs = PptxPresentation(str(pptx_path))

        # 既存スライドの数を記録（後で除外する）
        existing_count = len(prs.slides)

        for layout in prs.slide_layouts:
            prs.slides.add_slide(layout)

        prs.save(str(tmp_pptx))

        # レンダリング
        try:
            all_images = _pdf_to_images(
                _pptx_to_pdf(tmp_pptx, Path(tmpdir)),
                Path(tmpdir),
                dpi,
            )
        except Exception:
            return [Image.new("RGB", (320, 240), (240, 240, 240))] * layout_count

        # 既存スライド分をスキップして、レイアウトプレビュー部分だけ返す
        layout_images = all_images[existing_count:]

        previews = []
        for i in range(layout_count):
            if i < len(layout_images):
                previews.append(Image.open(layout_images[i]).copy())
            else:
                previews.append(Image.new("RGB", (320, 240), (240, 240, 240)))

        return previews


def check_libreoffice() -> bool:
    """LibreOfficeが利用可能か確認。"""
    try:
        _find_soffice()
        return True
    except RuntimeError:
        return False
